services:
  db:
    container_name: rcovery_client_management_db
    image: postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      PGDATA: /data/postgres
      POSTGRES_DB: devdb
    volumes:
      - db:/data/postgres
    ports:
      - "9001:5432"
    networks:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d devdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: rcovery_client_management_app
    image: golang:1.26-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DBHOST: db
      DBPORT: 5432
    ports:
      - "9000:9000"
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/app/docker-entrypoint.sh"]

networks:
  db:
    driver: bridge

volumes:
  db:
